version: '3.9'

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mididb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  api:
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app
    environment:
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mididb
    ports:
      - '8000:8000'
    depends_on:
      - db

  web:
    build: ./web
    command: npm run dev
    volumes:
      - ./web:/app
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - '3000:3000'
    depends_on:
      - api

volumes:
  pgdata:
